# Generated by Django 2.2.12 on 2020-04-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200415_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
